# Decap CMS Configuration
backend:
  name: github
  repo: ${NEXT_PUBLIC_GITHUB_REPO_FULL_NAME}
  branch: main
  base_url: ${NEXT_PUBLIC_SITE_URL}
  auth_endpoint: api/auth # This will be relative to base_url
  auth_type: implicit
  app_id: ${NEXT_PUBLIC_OAUTH_CLIENT_ID}

# Media and public folders
media_folder: /public/uploads
public_folder: /uploads
publish_mode: editorial_workflow

# Collections
collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home Page
        file: content/pages/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
      - name: hello
        label: Hello World Page
        file: content/pages/hello.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }