
backend:
  name: github
  repo: process.env.NEXT_PUBLIC_GITHUB_REPO_FULL_NAME
  branch: main
  auth_type: oauth
  base_url: process.env.NEXT_PUBLIC_SITE_URL
  auth_endpoint: 'api/auth'

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home Page'
        file: 'content/pages/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
      - name: 'hello'
        label: 'Hello Page'
        file: 'content/pages/hello.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
