backend:
  name: github
  repo: ${GITHUB_REPO_FULL_NAME}
  branch: main
  auth_type: pkce
  base_url: ${NEXT_PUBLIC_SITE_URL}
  auth_endpoint: api/auth?next=/admin

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
  - name: products
    label: Products
    folder: content/products
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: Description, name: description, widget: markdown }
      - { label: Price, name: price, widget: number, value_type: float }