
backend:
  name: github
  repo: RishiCo-Canna/RishiStaticNEXTsite
  branch: main
  auth_scope: repo
  base_url: "https://09947623-be9f-4899-956d-87e3e868f824-00-qam5g0scl8i3.worf.replit.dev"
  auth_endpoint: "/api/auth"

local_backend: false

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
