backend:
  name: github
  repo: ${GITHUB_REPO_FULL_NAME}
  branch: main
  base_url: ${NEXT_PUBLIC_SITE_URL}
  auth_endpoint: api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Description", name: "description", widget: "markdown", required: true }
      - { label: "Price", name: "price", widget: "number", value_type: "float", required: true }