backend:
  name: github
  repo: process.env.NEXT_PUBLIC_GITHUB_REPO_FULL_NAME
  branch: main
  base_url: '' # This will be set by the CMS component
  auth_endpoint: api/auth

local_backend: true
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home Page
        file: content/pages/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }