
backend:
  name: github
  repo: your-username/your-repo # Replace with your GitHub username/repo
  branch: main
  auth_type: pkce
  base_url: https://${process.env.REPLIT_DEV_DOMAIN}
  auth_endpoint: api/auth

media_folder: public/images
public_folder: /images

collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
