
backend:
  name: github
  repo: process.env.NEXT_PUBLIC_GITHUB_REPO_FULL_NAME
  branch: main
  auth_type: oauth
  base_url: 'https://api.github.com'
  auth_endpoint: 'api/auth'

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home Page
        file: content/pages/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
      - name: hello
        label: Hello World Page
        file: content/pages/hello.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown }
